github.com:
    users:
        TheTickingBomb:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: TheTickingBomb
