github.com:
    users:
        TheTickingBomb:
            oauth_token: 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
    git_protocol: https
    user: TheTickingBomb
    oauth_token: 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
